import sharp from 'sharp'
import { BackgroundResources } from './resources/background.mjs'
import { MiscResources } from './resources/misc.mjs'
import { localizations, servers } from './utils/servers.mjs'

export const generate = async (
    background: BackgroundResources,
    misc: MiscResources,
    packageName: string,
    packageVersion: string
) => {
    const name = `bandori-live-${background.name}`
    console.log('Generating', name, 'resources...')

    const info = getInfo(background.texts, packageName, packageVersion)
    const image = getImage(background.bgImage)
    const thumbnail = getThumbnail(background.bgImage)

    return {
        name,

        info,
        data: misc.data,
        configuration: misc.configuration,
        image,
        thumbnail,
    }
}

const getInfo = (texts: string[], packageName: string, packageVersion: string) => ({
    version: 2,
    title: Object.fromEntries(servers.map((_, i) => [localizations[i], texts[i]])),
    subtitle: {
        en: 'BanG Dream! Girls Band Party!',
        ja: 'バンドリ！ ガールズバンドパーティ！',
        ko: '뱅드림! 걸즈 밴드 파티!',
        zhs: 'BanG Dream! 少女乐团派对!',
        zht: 'BanG Dream! 少女樂團派對',
    },
    author: {
        en: 'Burrito',
    },
    description: {
        en: [
            'Generated by:',
            packageName,
            '',
            'Version:',
            packageVersion,
            '',
            'GitHub Repository:',
            'https://github.com/NonSpicyBurrito/sonolus-bandori-background-generator',
        ].join('\n'),
    },
})

const getImage = (bgImage: Buffer) =>
    sharp(bgImage)
        .resize(2048, 1024, { fit: 'fill' })
        .extract({ left: 0, top: 96, width: 2048, height: 576 })
        .png({ compressionLevel: 9 })

const getThumbnail = (bgImage: Buffer) =>
    sharp(bgImage)
        .resize(320, 320, { fit: 'fill' })
        .extract({ left: 32, top: 0, width: 256, height: 256 })
        .png({ compressionLevel: 9 })
